version: "3.9"

services:
  db:
    container_name: "db"
    env_file:
      - .env
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./confs/postgresql/my_postgresql.conf:/etc/postgresql/postgresql.conf

  adminer:
    container_name: "adminer"
    env_file:
      - .env
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER_PASSWORD$=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: ["sh", "-c",
              "mkdir -p /usr/local/etc/redis &&
              echo 'bind 0.0.0.0' > /usr/local/etc/redis/redis.conf &&
              echo 'requirepass $REDIS_PASSWORD' >> /usr/local/etc/redis/redis.conf &&
              echo 'appendonly yes' >> /usr/local/etc/redis/redis.conf &&
              echo 'appendfsync everysec' >> /usr/local/etc/redis/redis.conf &&
              echo 'user default on nopass ~* +@all' > /usr/local/etc/redis/users.acl &&
              echo 'user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all' >> /usr/local/etc/redis/users.acl &&
              redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl"]
    restart: unless-stopped

  api:
    container_name: "api"
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./alembic/versions:/alembic/versions
      - ./api:/api
